### ISSUE TITLE
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by XiangZhangPKU** [woodfrog/floor-sp#13]
Hi, thanks for publishing the great work.
I actually have difficulties to run the code. My environment is as below:
ubuntu 20.04
python 3.5.6
pytorch 0.4.0
cuda: 9.0.176
GPU: RTX2080

when I ran python ./mask_rcnn interface_corner.py, I got something like this:
`
loaded weights from ./logs/mask_rcnn_lianjia_dataset_0069.pth
/home/xiangzhang/Codes/floor-sp/mask-rcnn/model/model.py:1735: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  molded_images = Variable(molded_images, volatile=True)
Traceback (most recent call last):
  File "inference_corner.py", line 89, in <module>
    results = model.detect([image])
  File "/home/xiangzhang/Codes/floor-sp/mask-rcnn/model/model.py", line 1738, in detect
    detections, mrcnn_mask = self.predict([molded_images, image_metas], mode='inference')
  File "/home/xiangzhang/Codes/floor-sp/mask-rcnn/model/model.py", line 1775, in predict
    [p2_out, p3_out, p4_out, p5_out, p6_out] = self.fpn(molded_images)
  File "/home/xiangzhang/anaconda3/envs/floor-sp/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiangzhang/Codes/floor-sp/mask-rcnn/model/model.py", line 179, in forward
    x = self.C1(x)
  File "/home/xiangzhang/anaconda3/envs/floor-sp/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiangzhang/anaconda3/envs/floor-sp/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/xiangzhang/anaconda3/envs/floor-sp/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiangzhang/anaconda3/envs/floor-sp/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
`

Can anyone help on this? Thanks a lot!

**Comment by volodymyrkepsha** [comment]
is't it a problem ?
https://github.com/pytorch/pytorch/issues/17543

**Comment by XiangZhangPKU** [comment]
> is't it a problem ?
> [pytorch/pytorch#17543](https://github.com/pytorch/pytorch/issues/17543)

Thanks for your reply.
Yes, I think it's because of the incompatibility of cuda 9 and my graphic card. But to use this code, pytorch 0.4.0 is required and cuda version can't go higher than 9. So I guess either upgrading the code to fit higher pytorch version and cuda version or downgrading the graphic card is the solution for now...
