### ISSUE TITLE
Problem Downloading the data

### ISSUE THREAD

**Issue by marcomiglionico94** [woodfrog/floor-sp#22]
I followed the instructions on the README but when i run the script to download the file, it find the first path dataset%2Fpublic%2Fzip%2F0Kajc_nnyZ6K0cRGCQJW56.zip but then give me this error 
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
unzip:  cannot find or open zips/*.zip, zips/*.zip.zip or zips/*.zip.ZIP.

No zipfiles found.
`

**Comment by assankhanov** [comment]
Hello @marcomiglionico94,
I am using MAC OS, so I solved this problem by 

1. browsing to `Applications/Python[your python version]` 
2. running `Install Certificates.command`

I hope this will be helpful for you.

**Comment by tejaswivg** [comment]
You can also use a browser plugin such as [Downthemall](https://www.downthemall.net/) to download all the data after you get the email with links.

**Comment by weiXiaxvv** [comment]
I save the email as an HTML file and run sh download.sh. But this is the result:
Traceback (most recent call last):
  File "download_from_email.py", line 48, in <module>
    main(args)
  File "download_from_email.py", line 32, in main
    links = get_all_links(open(args.source))
  File "download_from_email.py", line 10, in get_all_links
    soup = BeautifulSoup(html, 'lxml')
  File "/home/wangqiting/.local/lib/python3.7/site-packages/bs4/__init__.py", line 251, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
unzip:  cannot find or open zips/*.zip, zips/*.zip.zip or zips/*.zip.ZIP.

Can you help me?

**Comment by W-Q-T** [comment]
If cannot download through .html, you can directly download the model compressed package to /data/public_100/zips and run unzip_all.sh to decompress it.

**Comment by thedevup** [comment]
> I save the email as an HTML file and run sh download.sh. But this is the result: Traceback (most recent call last): File "download_from_email.py", line 48, in main(args) File "download_from_email.py", line 32, in main links = get_all_links(open(args.source)) File "download_from_email.py", line 10, in get_all_links soup = BeautifulSoup(html, 'lxml') File "/home/wangqiting/.local/lib/python3.7/site-packages/bs4/**init**.py", line 251, in **init** % ",".join(features)) bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library? unzip: cannot find or open zips/_.zip, zips/_.zip.zip or zips/*.zip.ZIP.
> 
> Can you help me?

pip install lxml

After that download the email as an html file, name it 'email.html'
