### ISSUE TITLE
Run on cpu 

### ISSUE THREAD

**Issue by koji** [woodfrog/floor-sp#8]
Hi, thank you for sharing your great work.
I'm trying to run the project on macOS (without GPU).

When I run `mask-rcnn/inference_corner.py` got the following error.
Could you help me?

```
Traceback (most recent call last):
  File "mask-rcnn/inference_corner.py", line 4, in <module>
    import main
  File "/Users/koji.kanao/Desktop/floor-sp/mask-rcnn/main.py", line 46, in <module>
    import model.model as modellib
  File "/Users/koji.kanao/Desktop/floor-sp/mask-rcnn/model/model.py", line 27, in <module>
    from model.nms.nms_wrapper import nms
  File "/Users/koji.kanao/Desktop/floor-sp/mask-rcnn/model/nms/nms_wrapper.py", line 11, in <module>
    from model.nms.pth_nms import pth_nms
  File "/Users/koji.kanao/Desktop/floor-sp/mask-rcnn/model/nms/pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "/Users/koji.kanao/Desktop/floor-sp/mask-rcnn/model/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'model.nms._ext.nms._nms'
```

**Comment by woodfrog** [comment]
Hi, thank you for your interest!

You need to compile and build the NMS and RoIAlign before running. The Mask-RCNN part is based on a [public Mask-RCNN implementation](https://github.com/multimodallearning/pytorch-mask-rcnn), and the installation instruction can be checked [here](https://github.com/multimodallearning/pytorch-mask-rcnn#installation).

**Comment by koji** [comment]
@woodfrog Thank you so much!
